language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
notifications:
  email: false
  slack:
    secure: I1BuquShDtNXhCO05mSCFvXIJQ3zC8MfXCnDIlDYtaX0ZHW3FyE5anf1rvAtldibYKJBvkelPUJRxzAhUP/qTnC91EHch4XkKzk6T2emvqdV1wQ3dj1SC+xLBW4ZnL9iSRpixNaES0j+uDZwMs2rPjHvbiRp9guVRtjzTy/7+BQ=
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  on:
    all_branches: true
    tags: true
  api_key:
    secure: GAzOAm6V8QJirvBL+TOF5Zr23By7+sfTarDcZAvq1o3hCBh4RuJBGMTBwPyEtLrPHjQSGrc4W9OvRaYE+ikZ013RjVTs+6HGLfuRwuYfcfp2kjKT45IXkInUmHpYt6zamYRcl27vFi1Fq0EOMdleUJqKKWXUCQCec3Ki9f8CPb0=
env:
  global:
  - secure: Isk3RzrLjybnnWKs+mCVxKWbJtRitZ6GUD9S8jOkLfreHpBuxoOELo1JAwWm4anE5XjHuWYO9whcbJB8mzaTXGvcTsxvke1zE9VICyoigvkJmJZFJrLpC7Ls/7w5DHM8JitOn4W2aoNDmARdfCHmB2yoemXW6F+uPGbYn+rsQ0c=
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
sudo: false
cache:
  directories:
  - node_modules
